version: "3.1"

services:
    # Web service
    www:
        build: .
        ports: 
            - "80:80"  # Container port:Host port mapping
        volumes:
            - ./html:/var/www/html  # Volume mapping:Host folder:Container folder
        links:
            - db  # Link to the database service
        networks:
            - default  # Container network

    # Database
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"  # Container port:Host port mapping
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: billing # database name
            MYSQL_USER: admin_user # mysql user
            MYSQL_PASSWORD: # mysql password
            MYSQL_ROOT_PASSWORD: # mysqlpassword
        volumes:
            - ./dump:/docker-entrypoint-initdb.d  # Volume mapping for initial data import
            # - ./conf:/etc/mysql/conf.d  # Volume mapping for MySQL configuration
            - persistent:/var/lib/mysql  # Volume mapping for persistent data
        networks:
            - default  # Container network

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db  # Link to the database service
        ports:
            - 8000:80  # Container port:Host port mapping
        environment:
            MYSQL_USER: # your username
            MYSQL_PASSWORD: # password
            MYSQL_ROOT_PASSWORD: # root password

volumes:
    persistent:  # Name of the volume for persistent data
